version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO:latest .
      - docker tag $ECR_REPO:latest $ECR_REPO:latest
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $ECR_REPO:latest
      - printf '[{"name":"nuxt-container","imageUri":"%s"}]' $ECR_REPO:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json